config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :podcasts do
    resources :reviews
  end

  root to: 'podcasts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :podcasts
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  belongs_to :category
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :podcast
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :podcasts
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :find_podcast, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @podcasts = Podcast.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @podcasts = Podcast.where(:category_id => @category_id).order('created_at DESC')
    end
  end

  def show
     @podcast = Podcast.find(params[:id])
  end

  def new
    @podcast = current_user.podcasts.build
    @categories = Category.all.map { |category| [category.name, category.id] }
  end

  def create
    @podcast = current_user.podcasts.build(podcast_params)
    @podcast.category = Category.find(params[:category_id])

    if @podcast.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all.map { |category| [category.name, category.id] }
  end

  def update
   # @podcast.category = Category.find(params[:category_id])

    if @podcast.update(podcast_params)
      redirect_to podcast_path(@podcast)
    else
      render :edit
    end
  end

  def destroy
    @podcast.destroy
    redirect_to root_path
  end

  private

  def podcast_params
    params.require(:podcast).permit(:title, :description, :author, :category_id, :photo)
  end

  def find_podcast
    @podcast = Podcast.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_podcast
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.podcast = Podcast.find(params[:podcast_id])
    @review.user = current_user

    if @review.save
      redirect_to podcast_path(@podcast)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_podcast
    @podcast = Podcast.find(params[:podcast_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Podcast Reviewzzz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="fontawesome-stars.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/podcasts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for @podcast, :html =>  { :multipart => true } do |f| %>
          <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category" ) %>
          <%= f.input :title, label: "Podcast Name" %>
          <%= f.input :description %>
          <%= f.input :photo, as: :file %>
          <%= f.input :author %>
          <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/podcasts/edit.html.erb
<h1>Edit a podcast </h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for @podcast, :html =>  { :multipart => true } do |f| %>
          <%= f.select :category_id, @categories %>
          <%= f.input :title, label: "Podcast Name" %>
          <%= f.input :description %>
          <%= f.input :author %>
          <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/podcasts/index.html.erb
<h1 class="current_category"><%= params[:category] %></h1>

  <% if @podcasts.count == 0 %>
    <h1>No Podcasts here!</h1>
  <% else %>
  <div class="row">
    <% @podcasts.each do |podcast| %>
      <div class="col-md-3">
        <% if podcast.photo.attached? %>
          <%= link_to podcast_path(podcast) do %>
            <%= cl_image_tag podcast.photo.key, class: 'podcast' %>
          <% end %>
        <% else %>
          <h2> <%= link_to podcast.title, podcast_path(podcast)%></h2>
        <% end %>
      </div>
    <% end %>
  </div>
  <% end %>

app/views/podcasts/new.html.erb
<h1>New Pocast</h1>

<%= render 'form' %>

app/views/podcasts/show.html.erb
<div class="row">
  <div class="col-md-4">
    <% if @podcast.photo.attached? %>
        <%= cl_image_tag @podcast.photo.key, class: "podcast-show" %>
    <% else %>
        <%= simple_form_for @podcast, :html =>  { :multipart => true } do |f| %>
          <%= f.input :photo, as: :file %>
          <%= f.submit :button %>
        <% end %>
    <% end %>
  </div>
  <div class="col-md-8">
    <h2><%= @podcast.title %></h2>
    <h3><%= @podcast.author %> </h3>
    <p><%= @podcast.description %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <%= render @podcast.reviews %>
  </div>
</div>

<%= link_to "Add review", new_podcast_review_path(@podcast) %>
<%= link_to "Back", root_path %>
  <% if user_signed_in? %>
    <% if @podcast.user_id = current_user.id %>
      <%= link_to "Edit", edit_podcast_path(@podcast) %>
      <%= link_to "Delete", podcast_path(@podcast), method: :delete, data: { confirm: "Are you sure?"}  %>
    <% end %>
<% end %>

app/views/reviews/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for([@podcast, @podcast.reviews.build]) do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
        <%= f.submit "Send your review" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<p><%= review.content %></p>

app/views/reviews/new.html.erb
<h1>New Review ew</h1>

<%= render 'form' %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "Podcastz Review", root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% Category.all.each do |category| %>
              <%= link_to category.name, podcasts_path(category: category.name), class:"dropdown-item" %>
            <% end %>
         </div>
          <li class="nav-item active">
            <%= link_to "Add Podcast", new_podcast_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>